name: custom_ternary_lint
description: Custom linter to filter ternary operators.
version: 1.0.0
repository: https://github.com/lezli01/custom_ternary_lint

environment:
  sdk: ^3.9.0

dependencies:
  custom_lint_builder: ^0.8.1
  analyzer: ^8.4.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
